schema_version: 1

context:
  name: types-croniter
  version: 6.0.0.20250809

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name | replace('-', '_') }}-${{ version }}.tar.gz
  sha256: c829295d4d65eaddcfafec905b0fbab59e72c3c91ee934a4d504dcafad79ff95

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python >=${{ python_min }}
    - setuptools
  run:
    - python >=${{ python_min }}

tests:
  - requirements:
      run:
        - pip
        - python >=${{ python_min }}
    script:
      - pip check

  - package_contents:
      site_packages:
        - croniter-stubs/__init__.pyi

about:
  summary: Typing stubs for croniter
  license: Apache-2.0 AND MIT
  license_file: LICENSE
  homepage: https://github.com/python/typeshed

extra:
  recipe-maintainers:
    - fhoehle
    - conda-forge/mypy
